"""Build the AgentUX brand assets from code.

Everything in brand/svg, brand/png and brand/art is generated by this script:
the mark is geometry, the wordmark is Martian Mono converted to outlines, so
none of the SVGs depends on an installed font.

Requirements (only to regenerate; the outputs are committed):
  pip install fonttools pillow
  npm install @resvg/resvg-js         (in this directory, for SVG -> PNG)
  Martian Mono variable font (OFL), e.g.
  https://raw.githubusercontent.com/google/fonts/main/ofl/martianmono/MartianMono%5Bwdth%2Cwght%5D.ttf
  saved as brand/src/MartianMono.ttf (not committed)

Usage: python brand/src/build.py
"""

import math
import os
import random
import subprocess
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

SRC = Path(__file__).resolve().parent
BRAND = SRC.parent
FONT = SRC / "MartianMono.ttf"

# ---- palette -----------------------------------------------------------------
LIME = "#c6f36b"      # Signal: the accent, cockpit --accent, Plasma AccentColor
INK = "#0b0d10"       # Ink: cockpit --bg, Plymouth background
GRAPHITE = "#171b20"  # Graphite: cockpit --surface-2, raised dark surfaces
MIST = "#e7eaef"      # Mist: cockpit --text, text on Ink
MOSS = "#4f7d0b"      # Moss: the accent on light backgrounds (cockpit light --accent)
PAPER = "#f4f5f7"     # Paper: cockpit light --bg
SLATE = "#949dab"     # Slate: secondary text on Ink (cockpit --text-muted)
SLATE_L = "#5a6370"   # secondary text on Paper (cockpit light --text-muted)

SVG_NS = 'xmlns="http://www.w3.org/2000/svg"'


# ---- the mark ----------------------------------------------------------------
# "The merge": four lanes, one per agent, converge into one line. Drawn on a
# 64-unit grid; the glyph spans x 5.5..58.5, y 10.5..53.5 including caps.
LANE_Y = (13.0, 25.0 + 2 / 3, 38.0 + 1 / 3, 51.0)
LANE_X0 = 8.0
JOIN_X = 38.0
TRUNK_X1 = 56.0
STROKE = 5.0
TRUNK = 6.0


def mark_paths(color, stroke=STROKE, trunk=TRUNK):
    lanes = []
    for y in LANE_Y:
        c1 = LANE_X0 + (JOIN_X - LANE_X0) * 0.55
        c2 = JOIN_X - (JOIN_X - LANE_X0) * 0.55
        lanes.append(f"M{LANE_X0:g} {y:.3f}C{c1:.2f} {y:.3f} {c2:.2f} 32 {JOIN_X:g} 32")
    return (
        f'<g fill="none" stroke="{color}" stroke-linecap="round">'
        f'<path stroke-width="{stroke:g}" d="{" ".join(lanes)}"/>'
        f'<path stroke-width="{trunk:g}" d="M{JOIN_X - 2:g} 32H{TRUNK_X1:g}"/>'
        f"</g>"
    )


OPTICAL_DX = 1.5  # the lanes carry more weight than the trunk: nudge right to centre


def tile(fg=INK, bg=LIME, rx=13.5, scale=0.74, inset=3.0):
    """Rounded tile with the glyph, on the 64 grid (app icon). `inset` leaves a
    transparent margin, as desktop icon themes do."""
    size = 64 - 2 * inset
    return (
        f'<rect x="{inset:g}" y="{inset:g}" width="{size:g}" height="{size:g}" rx="{rx}" fill="{bg}"/>'
        f'<g transform="translate({32 + OPTICAL_DX * scale:.3f} 32) scale({scale}) translate(-32 -32)">'
        f'{mark_paths(fg)}</g>'
    )


# ---- type ----------------------------------------------------------------------
_fonts = {}


def font(wght, wdth=100):
    key = (wght, wdth)
    if key not in _fonts:
        if not FONT.exists():
            sys.exit(f"missing {FONT}; see the docstring")
        f = TTFont(FONT)
        _fonts[key] = instantiateVariableFont(f, {"wght": wght, "wdth": wdth}, inplace=False)
    return _fonts[key]


def text_path(text, size, wght=700, wdth=100, tracking=0.0):
    """Outline text. Baseline at y=0 (y down). Returns d, advance, bounds, cap height."""
    f = font(wght, wdth)
    gs = f.getGlyphSet()
    cmap = f.getBestCmap()
    upm = f["head"].unitsPerEm
    s = size / upm
    x = 0.0
    pen = SVGPathPen(gs)
    bp = BoundsPen(gs)
    for i, ch in enumerate(text):
        g = gs[cmap[ord(ch)]]
        t = (s, 0, 0, -s, x, 0)
        g.draw(TransformPen(pen, t))
        g.draw(TransformPen(bp, t))
        x += g.width * s + (tracking * size if i + 1 < len(text) else 0)
    cap = f["OS/2"].sCapHeight * s
    return pen.getCommands(), x, bp.bounds, cap


WORD = dict(wght=720, wdth=100, tracking=-0.035)


def wordmark(size, color):
    d, adv, b, cap = text_path("AgentUX", size, **WORD)
    return f'<path fill="{color}" d="{d}"/>', adv, b, cap


def lockup(mark_color, word_color, cap_target=100.0):
    """Horizontal lockup. Returns (inner svg, width, height); origin top-left."""
    # Size the type so its cap height is cap_target.
    _, _, _, cap1 = text_path("A", 100, wght=WORD["wght"], wdth=WORD["wdth"])
    size = 100 * cap_target / cap1
    word, adv, b, cap = wordmark(size, word_color)
    # Mark: glyph height (lane caps outside to outside, 43 units) = 1.32 x cap height.
    k = cap * 1.32 / 43.0
    mark_w = 53.0 * k          # 5.5..58.5
    gap = cap * 0.62
    pad_top = 0.0
    # Vertical centre of the mark = centre of the cap height.
    height = max(43.0 * k, cap - b[1] if b[1] < 0 else cap) + (b[3] if b[3] > 0 else 0)
    top = 0.0
    cap_mid = 43.0 * k / 2      # mark spans 0..43k; text baseline sits so caps centre on it
    baseline = cap_mid + cap / 2
    descent = max(b[3], 0)
    height = max(43.0 * k, baseline + descent)
    mark = f'<g transform="translate({-5.5 * k:.3f} {-10.5 * k:.3f}) scale({k:.5f})">{mark_paths(mark_color)}</g>'
    text = f'<g transform="translate({mark_w + gap - b[0]:.3f} {baseline:.3f})">{word}</g>'
    width = mark_w + gap + (b[2] - b[0])
    return mark + text, width, height


# ---- lanes field (wallpaper, banner, social card) -------------------------------
def lanes_field(w, h, join, n, seed, base_color, base_alpha, hi_color, hi_alpha,
                hi_width, base_width, spread=None, hi_span=0.46, packets=3):
    """Many faint lanes enter from the left edge and end where they meet at `join`;
    four highlighted lanes repeat the mark and continue as one line to the right
    edge. A few short bright dashes travel the highlighted lanes: messages on the bus."""
    rnd = random.Random(seed)
    jx, jy = join
    spread = spread or (-0.08 * h, 1.08 * h)
    out = []
    ys = [spread[0] + (spread[1] - spread[0]) * (i + 0.5) / n for i in range(n)]
    for i, y0 in enumerate(ys):
        y0 += rnd.uniform(-0.35, 0.35) * (spread[1] - spread[0]) / n
        x0 = -0.02 * w - rnd.uniform(0, 0.05) * w
        k1 = rnd.uniform(0.42, 0.62)
        k2 = rnd.uniform(0.45, 0.65)
        c1x = x0 + (jx - x0) * k1
        c2x = jx - (jx - x0) * k2
        d = f"M{x0:.1f} {y0:.1f}C{c1x:.1f} {y0:.1f} {c2x:.1f} {jy:.1f} {jx:.1f} {jy:.1f}"
        a = base_alpha * rnd.uniform(0.55, 1.25)
        out.append(f'<path d="{d}" stroke="{base_color}" stroke-opacity="{a:.3f}" '
                   f'stroke-width="{base_width * rnd.uniform(0.8, 1.2):.2f}"/>')
    # the four lanes of the mark, drawn large, joining into one line
    span = (spread[1] - spread[0]) * hi_span
    x0 = jx - span * 1.55
    hi = []
    for j in range(4):
        y0 = jy - span / 2 + span * j / 3
        c1x = x0 + (jx - x0) * 0.55
        c2x = jx - (jx - x0) * 0.55
        d = f"M{x0:.1f} {y0:.1f}C{c1x:.1f} {y0:.1f} {c2x:.1f} {jy:.1f} {jx:.1f} {jy:.1f}"
        hi.append(d)
        out.append(f'<path d="{d}" stroke="{hi_color}" stroke-opacity="{hi_alpha:.3f}" '
                   f'stroke-width="{hi_width:.2f}"/>')
        out.append(f'<circle cx="{x0:.1f}" cy="{y0:.1f}" r="{hi_width * 2.2:.1f}" fill="{hi_color}" '
                   f'fill-opacity="{hi_alpha:.3f}"/>')
    trunk = f"M{jx:.1f} {jy:.1f}H{w * 1.02:.1f}"
    out.append(f'<path d="{trunk}" stroke="{hi_color}" stroke-opacity="{hi_alpha:.3f}" '
               f'stroke-width="{hi_width * 1.3:.2f}"/>')
    # messages: short brighter dashes on the highlighted lanes and the trunk
    lane_len = (jx - x0) * 1.12
    for j, d in enumerate(hi[:packets] if packets else []):
        pick = [1, 3, 0, 2][j % 4]
        d = hi[pick]
        dash = lane_len * 0.07
        off = -lane_len * rnd.uniform(0.2, 0.75)
        out.append(f'<path d="{d}" stroke="{hi_color}" stroke-width="{hi_width * 2.4:.2f}" '
                   f'stroke-dasharray="{dash:.1f} {lane_len * 4:.0f}" stroke-dashoffset="{off:.1f}"/>')
    if packets:
        tl = w - jx
        out.append(f'<path d="{trunk}" stroke="{hi_color}" stroke-width="{hi_width * 2.8:.2f}" '
                   f'stroke-dasharray="{lane_len * 0.09:.1f} {tl * 4:.0f}" '
                   f'stroke-dashoffset="{-tl * 0.38:.1f}"/>')
    return f'<g fill="none" stroke-linecap="round">{"".join(out)}</g>'


# ---- writers -------------------------------------------------------------------
def svg(w, h, body, title=None, vb=None):
    t = f"<title>{title}</title>" if title else ""
    vb = vb or f"0 0 {w:g} {h:g}"
    return (f'<svg {SVG_NS} width="{w:g}" height="{h:g}" viewBox="{vb}">{t}{body}</svg>\n')


def write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def render(svg_path, png_path, width):
    Path(png_path).parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["node", str(SRC / "render.mjs"), str(svg_path), str(png_path), str(width)],
                   check=True, cwd=SRC)


def main():
    out_svg = BRAND / "svg"
    out_png = BRAND / "png"
    art = BRAND / "art"

    # Mark, free-standing
    for name, color in [("mark-lime", LIME), ("mark-moss", MOSS), ("mark-ink", INK),
                        ("mark-black", "#000000"), ("mark-white", "#ffffff")]:
        p = write(out_svg / f"{name}.svg", svg(64, 64, mark_paths(color), "AgentUX"))
        if name in ("mark-lime", "mark-ink", "mark-white"):
            for s in (128, 256, 512):
                render(p, out_png / f"{name}-{s}.png", s)

    # App icon / favicon tile
    p = write(out_svg / "icon.svg", svg(64, 64, tile(), "AgentUX"))
    render(p, out_png / "icon-1024.png", 1024)
    for s in (16, 32, 48, 64, 128, 256):
        render(p, out_png / f"icon-{s}.png", s)
    # Small-size tile: heavier strokes and less padding so 16 px stays crisp
    small = (f'<rect width="64" height="64" rx="14" fill="{LIME}"/>'
             f'<g transform="translate({32 + OPTICAL_DX * 0.86:.3f} 32) scale(0.86) translate(-32 -32)">'
             f'{mark_paths(INK, stroke=6.2, trunk=7.0)}</g>')
    p = write(out_svg / "favicon.svg", svg(64, 64, small, "AgentUX"))
    for s in (16, 32):
        render(p, out_png / f"favicon-{s}.png", s)

    # Org avatar: full bleed, glyph inside the inscribed circle
    av = (f'<rect width="64" height="64" fill="{LIME}"/>'
          f'<g transform="translate({32 + OPTICAL_DX * 0.62:.3f} 32) scale(0.62) translate(-32 -32)">'
          f'{mark_paths(INK)}</g>')
    p = write(out_svg / "avatar.svg", svg(64, 64, av, "AgentUX"))
    render(p, out_png / "avatar-512.png", 512)

    # Wordmark
    for name, color in [("wordmark-mist", MIST), ("wordmark-ink", INK),
                        ("wordmark-black", "#000000"), ("wordmark-white", "#ffffff")]:
        body, adv, b, cap = wordmark(100, color)
        w = b[2] - b[0]
        h = b[3] - b[1]
        write(out_svg / f"{name}.svg",
              svg(round(w, 2), round(h, 2), f'<g transform="translate({-b[0]:.3f} {-b[1]:.3f})">{body}</g>',
                  "AgentUX", vb=f"0 0 {w:.2f} {h:.2f}"))

    # Lockups
    lockups = {
        "lockup-dark": (LIME, MIST),     # on Ink / dark backgrounds
        "lockup-light": (MOSS, INK),     # on Paper / light backgrounds
        "lockup-black": ("#000000", "#000000"),
        "lockup-white": ("#ffffff", "#ffffff"),
    }
    for name, (mc, wc) in lockups.items():
        body, w, h = lockup(mc, wc)
        p = write(out_svg / f"{name}.svg", svg(round(w, 2), round(h, 2), body, "AgentUX",
                                                 vb=f"0 0 {w:.2f} {h:.2f}"))
        if name in ("lockup-dark", "lockup-light"):
            render(p, out_png / f"{name}-1200.png", 1200)

    # Social preview 1280 x 640
    write(out_svg / "social.svg", social())
    render(out_svg / "social.svg", out_png / "social-1280x640.png", 1280)

    # Profile banners (also copied into the .github repo)
    for theme in ("dark", "light"):
        p = write(out_svg / f"banner-{theme}.svg", banner(theme))
        render(p, out_png / f"banner-{theme}.png", 1280)

    # Wallpaper key art (the Plasma wallpaper package is rendered from these)
    for theme in ("dark", "light"):
        p = write(art / f"wallpaper-{theme}.svg", wallpaper(theme, 3840, 2160))
        render(p, art / f"wallpaper-{theme}-preview.png", 1280)


def tagline(size, color, wght=400):
    d, adv, b, cap = text_path("The Linux distribution where every coding agent works as one team.",
                               size, wght=wght, wdth=100, tracking=-0.01)
    return f'<path fill="{color}" d="{d}"/>', adv, b


def social():
    W, H = 1280, 640
    field = lanes_field(W, H, (900, 450), 46, 7, MIST, 0.07, LIME, 0.9, 3.0, 1.4,
                        spread=(-40, 700), hi_span=0.4, packets=2)
    body, lw, lh = lockup(LIME, MIST, cap_target=58)
    tag, tw, tb = tagline(22, SLATE)
    return svg(W, H,
               f'<rect width="{W}" height="{H}" fill="{INK}"/>'
               f'<rect width="{W}" height="{H}" fill="url(#v)"/>'
               f'<defs><linearGradient id="v" x1="0" y1="0" x2="1" y2="0">'
               f'<stop offset="0" stop-color="{INK}" stop-opacity="0"/>'
               f'<stop offset="1" stop-color="{INK}" stop-opacity="0"/></linearGradient></defs>'
               f'{field}'
               f'<rect x="0" y="0" width="{W}" height="300" fill="url(#fadeTop)"/>'
               f'<defs><linearGradient id="fadeTop" x1="0" y1="0" x2="0" y2="1">'
               f'<stop offset="0" stop-color="{INK}" stop-opacity="0.92"/>'
               f'<stop offset="1" stop-color="{INK}" stop-opacity="0"/></linearGradient></defs>'
               f'<g transform="translate(88 92)">{body}</g>'
               f'<g transform="translate(90 {92 + lh + 48})">{tag}</g>',
               "AgentUX")


def banner(theme):
    """Profile banner: the field's four lanes are the mark, drawn large; their
    line runs into the wordmark."""
    W, H = 1280, 320
    if theme == "dark":
        bg, base, hi, wc, tc, ba = INK, MIST, LIME, MIST, SLATE, 0.075
    else:
        bg, base, hi, wc, tc, ba = PAPER, INK, MOSS, INK, SLATE_L, 0.10
    jy = 150
    field = lanes_field(W, H, (400, jy), 34, 11, base, ba, hi, 1.0, 3.2, 1.2,
                        spread=(-30, 350), hi_span=0.46, packets=2)
    # keep the field to the left of the wordmark: the trunk stops at x=520
    field = field.replace(f"H{W * 1.02:.1f}", "H520")
    word, adv, b, cap = wordmark(1, wc)
    size = 64 / cap   # cap height 64 px
    word, adv, b, cap = wordmark(size, wc)
    x = 560
    base_y = jy + cap / 2
    l1, w1, b1 = tagline_text("The Linux distribution where every coding agent", 19, tc)
    l2, w2, b2 = tagline_text("works as one team.", 19, tc)
    return svg(W, H,
               f'<clipPath id="c"><rect width="{W}" height="{H}" rx="16"/></clipPath>'
               f'<g clip-path="url(#c)"><rect width="{W}" height="{H}" fill="{bg}"/>{field}</g>'
               f'<g transform="translate({x - b[0]:.2f} {base_y:.2f})">{word}</g>'
               f'<g transform="translate({x + 2} {base_y + 62:.2f})">{l1}</g>'
               f'<g transform="translate({x + 2} {base_y + 92:.2f})">{l2}</g>',
               "AgentUX: the Linux distribution where every coding agent works as one team")


def tagline_text(text, size, color, wght=400):
    d, adv, b, cap = text_path(text, size, wght=wght, wdth=100, tracking=-0.01)
    return f'<path fill="{color}" d="{d}"/>', adv, b


def wallpaper(theme, W, H):
    if theme == "dark":
        bg0, bg1, base, hi, ba, ha = "#0e1115", INK, MIST, LIME, 0.055, 0.62
    else:
        bg0, bg1, base, hi, ba, ha = "#f7f8f9", "#eceef1", INK, MOSS, 0.07, 0.7
    jx, jy = W * 0.66, H * 0.56
    field = lanes_field(W, H, (jx, jy), 120, 3, base, ba, hi, ha, W / 1100, W / 2600,
                        spread=(-0.12 * H, 1.12 * H), packets=3)
    return svg(W, H,
               f'<defs><radialGradient id="bg" cx="{jx / W:.3f}" cy="{jy / H:.3f}" r="0.9">'
               f'<stop offset="0" stop-color="{bg0}"/><stop offset="1" stop-color="{bg1}"/>'
               f'</radialGradient></defs>'
               f'<rect width="{W}" height="{H}" fill="url(#bg)"/>{field}',
               "AgentUX")


if __name__ == "__main__":
    main()
